FROM dev_ait_template_for_aithub-airc_developer:0.1
LABEL maintainer="AIST"

RUN pip install pip-licenses

ENTRYPOINT [ "pip-licenses", "--format=plain-vertical", "--with-license-file", "--no-license-path" ]
